combine_control_expr = false
wrap_comments = true
comment_width = 100
force_explicit_abi = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "Vertical"
max_width = 100
merge_derives = true
imports_granularity = "Item"
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 1
tab_spaces = 4
unstable_features = true
use_try_shorthand = true
skip_macro_invocations = ["asm", "naked_asm", "macro_rules", "global_asm"]
use_small_heuristics = "Off"