combine_control_expr = false
wrap_comments = true
comment_width = 100
force_explicit_abi = true
hex_literal_case = "Lower"
max_width = 100
merge_derives = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 1
tab_spaces = 4
unstable_features = true
use_try_shorthand = true
skip_macro_invocations = ["asm", "naked_asm", "macro_rules", "global_asm"]
use_small_heuristics = "Off"
format_strings = true
format_macro_matchers = true
format_code_in_doc_comments = true
